page:
  type: list
  title: "Prompts"
links:
  - url: "./caveman/"
    title: "Caveman header"
    description: "Keep to essentials, no fluff"
  - url: "https://chat.deepseek.com/a/chat/s/45e3212d-5a74-4f5b-a45f-1d13c01530d4"
    title: "Image prompt structuring"
    description: "(deepseek session)"
