page:
  type: "kanji"
  title: "Глаголы"

kanji:
 - char: "行"
   readings: "い, こう"
   meaning: "Идти, ехать"
   examples:
     - kanji: "行く"
       reading: "いく"
       meaning: "Идти, ехать"
     - kanji: "旅行"
       reading: "りょこう"
       meaning: "Путешествие"
     - kanji: "銀行"
       reading: "ぎんこう"
       meaning: "Банк"

 - char: "来"
   readings: "く, らい"
   meaning: "Приходить, прибывать"
   examples:
     - kanji: "来る"
       reading: "くる"
       meaning: "Приходить"
     - kanji: "来年"
       reading: "らいねん"
       meaning: "Следующий год"
     - kanji: "来日"
       reading: "らいにち"
       meaning: "Прибытие в Японию"

 - char: "見"
   readings: "み, けん"
   meaning: "Видеть, смотреть"
   examples:
     - kanji: "見る"
       reading: "みる"
       meaning: "Видеть, смотреть"
     - kanji: "見物"
       reading: "けんぶつ"
       meaning: "Осмотр, экскурсия, лицезрение"
     - kanji: "意見"
       reading: "いけん"
       meaning: "Мнение, взгляд"

 - char: "聞"
   readings: "き, ぶん"
   meaning: "Слышать, слушать"
   examples:
     - kanji: "聞く"
       reading: "きく"
       meaning: "Слышать, слушать, спрашивать"
     - kanji: "新聞"
       reading: "しんぶん"
       meaning: "Газета"
     - kanji: "聞き手"
       reading: "ききて"
       meaning: "Слушатель"

 - char: "食"
   readings: "た, しょく"
   meaning: "Есть, кушать"
   examples:
     - kanji: "食べる"
       reading: "たべる"
       meaning: "Есть, кушать"
     - kanji: "食事"
       reading: "しょくじ"
       meaning: "Приём пищи, еда, трапеза"
     - kanji: "朝食"
       reading: "ちょうしょく"
       meaning: "Завтрак"

 - char: "飲"
   readings: "の, いん"
   meaning: "Пить"
   examples:
     - kanji: "飲む"
       reading: "のむ"
       meaning: "Пить"
     - kanji: "飲料"
       reading: "いんりょう"
       meaning: "Напиток"
     - kanji: "飲酒"
       reading: "いんしゅ"
       meaning: "Распитие спиртных напитков"

 - char: "立"
   readings: "た, りつ"
   meaning: "Вставать, стоять"
   examples:
     - kanji: "立つ"
       reading: "たつ"
       meaning: "Вставать, стоять"
     - kanji: "起立"
       reading: "きりつ"
       meaning: "Вставание"
     - kanji: "立場"
       reading: "たちば"
       meaning: "Положение, позиция"

 - char: "座"
   readings: "すわ, ざ"
   meaning: "Сидеть"
   examples:
     - kanji: "座る"
       reading: "すわる"
       meaning: "Сидеть"
     - kanji: "座席"
       reading: "ざせき"
       meaning: "Сиденье, место для сидения"
     - kanji: "正座"
       reading: "せいざ"
       meaning: "Сидение на коленях"

 - char: "走"
   readings: "はし, そう"
   meaning: "Бежать"
   examples:
     - kanji: "走る"
       reading: "はしる"
       meaning: "Бежать"
     - kanji: "走行"
       reading: "そうこう"
       meaning: "Движение, ход, пробег"

 - char: "書"
   readings: "か, しょ"
   meaning: "Писать"
   examples:
     - kanji: "書く"
       reading: "かく"
       meaning: "Писать"
     - kanji: "教科書"
       reading: "きょうかしょ"
       meaning: "Учебник"
     - kanji: "書類"
       reading: "しょるい"
       meaning: "Документы, бумаги, письменные материалы"
