page:
  title: 日本語
  type: list
links:
  - url: https://learnjapaneseaz.com/
    title: LearnjapaneseAZ
    description: Some learning materials
  - url: https://jisho.org/
    title: jisho
    description: Vocabulary (for kanji and words)
  - url: ./kanji/n5
    title: "漢字 N5"
    description: "漢字 N5"
  - url: ./kanji/n4
    title: "漢字 N4"
    description: "漢字 N4"


