page:
  title: 日本語
  type: list
links:
  - url: https://learnjapaneseaz.com/
    title: LearnjapaneseAZ
    description: Some learning materials
  - url: https://jisho.org/
    title: Vocabulary (for kanji and words)
    description: ""
  - url: ./kanji/01
    title: Learning kanji
    description: Address

