page:
  title: 日本語
  type: list
links:
  - url: https://learnjapaneseaz.com/
    title: LearnjapaneseAZ
    description: Some learning materials
  - url: https://jisho.org/
    title: jisho
    description: Vocabulary (for kanji and words)
  - url: ./kanji/n4/01
    title: Learning kanji
    description: Address

