page:
  type: list
  title: "Web AI"
assets:
  root: ".."
links:
  - url: "https://chat.deepseek.com/"
    title: "Deepseek"
    description: "Into the unknown"
  - url: "https://yandex.ru/alice/"
    title: "Alice AI"
    description: "Чем помочь сегодня?"
  - url: "https://shedevrum.ai/text-to-image/"
    title: "Шедеврум"
    description: "Создать изображение"
  - url: "https://www.kimi.com/chat/"
    title: "KIMI"
    description: "Kimi chat"
