page:
  type: "kanji"
  title: "Люди"

kanji:
 - char: "人"
   readings: "ひと, じん, にん"
   meaning: "Человек"
   examples:
     - kanji: "日本人"
       reading: "にほんじん"
       meaning: "Японец"
     - kanji: "一人"
       reading: "ひとり"
       meaning: "Один человек"
     - kanji: "人気"
       reading: "にんき"
       meaning: "Популярность"

 - char: "男"
   readings: "おとこ, だん"
   meaning: "Мужчина"
   examples:
     - kanji: "男の人"
       reading: "おとこのひと"
       meaning: "Мужчина"
     - kanji: "男子"
       reading: "だんし"
       meaning: "Мальчик, юноша, мужчина"
     - kanji: "男性"
       reading: "だんせい"
       meaning: "Мужской пол, мужчина"

 - char: "女"
   readings: "おんな, じょ"
   meaning: "Женщина"
   examples:
     - kanji: "女の人"
       reading: "おんなのひと"
       meaning: "Женщина"
     - kanji: "女子"
       reading: "じょし"
       meaning: "Девочка, девушка, женщина"
     - kanji: "女性"
       reading: "じょせい"
       meaning: "Женский пол, женщина"

 - char: "子"
   readings: "こ, し"
   meaning: "Ребенок"
   examples:
     - kanji: "子供"
       reading: "こども"
       meaning: "Ребенок, дети"
     - kanji: "息子"
       reading: "むすこ"
       meaning: "Сын"
     - kanji: "女子"
       reading: "じょし"
       meaning: "Девочка, девушка"

 - char: "友"
   readings: "とも, ゆう"
   meaning: "Друг"
   examples:
     - kanji: "友達"
       reading: "ともだち"
       meaning: "Друг, товарищ"
     - kanji: "友人"
       reading: "ゆうじん"
       meaning: "Друг"
     - kanji: "親友"
       reading: "しんゆう"
       meaning: "Близкий друг, лучший друг"

 - char: "先生"
   readings: "せんせい"
   meaning: "Учитель, наставник"
   examples:
     - kanji: "先生"
       reading: "せんせい"
       meaning: "Учитель, преподаватель"
     - kanji: "医者"
       reading: "いしゃ"
       meaning: "Врач"
     - kanji: "学校の先生"
       reading: "がっこうのせんせい"
       meaning: "Школьный учитель"

 - char: "学"
   readings: "がく, まな"
   meaning: "Учеба, изучение"
   examples:
     - kanji: "学生"
       reading: "がくせい"
       meaning: "Студент, учащийся"
     - kanji: "学校"
       reading: "がっこう"
       meaning: "Школа"
     - kanji: "学習"
       reading: "がくしゅう"
       meaning: "Обучение, изучение"

 - char: "校"
   readings: "こう"
   meaning: "Школа"
   examples:
     - kanji: "学校"
       reading: "がっこう"
       meaning: "Школа"
     - kanji: "高校"
       reading: "こうこう"
       meaning: "Старшая школа"
     - kanji: "小学校"
       reading: "しょうがっこう"
       meaning: "Начальная школа"

 - char: "父"
   readings: "ちち, ふ"
   meaning: "Отец"
   examples:
     - kanji: "お父さん"
       reading: "おとうさん"
       meaning: "Папа"
     - kanji: "父"
       reading: "ちち"
       meaning: "Мой отец"
     - kanji: "父母"
       reading: "ふぼ"
       meaning: "Отец и мать, родители"

 - char: "母"
   readings: "はは, ぼ"
   meaning: "Мать"
   examples:
     - kanji: "お母さん"
       reading: "おかあさん"
       meaning: "Мама"
     - kanji: "母"
       reading: "はは"
       meaning: "Моя мать"
     - kanji: "母国"
       reading: "ぼこく"
       meaning: "Родина"
