page:
  title: 漢字 N4
  type: list
links:
  - url: ./01
    title: Адрес
    description: ""
  - url: ./02
    title: "Прилагательные, 1"
    description: ""
  - url: ./03
    title: "Прилагательные, 2"
    description: ""

