page:
  title: 漢字 N4
  type: list
links:
  - url: ./01
    title: Адрес
    description: ""
  - url: ./02
    title: "Прилагательные, 1"
    description: ""
  - url: ./03
    title: "Прилагательные, 2"
    description: ""
  - url: ./04
    title: "Прилагательные, 3"
    description: "低 広 短 良 悪 正 変 赤 青 黒"
  - url: ./05
    title: "Хобби"
    description: "映 画 音 楽 歌 写 真 旅 世 界"
  - url: ./06
    title: "Профессии"
    description: "仕 事 銀 員 医 働 者 屋 産 業"
