page:
  title: Manga reading
  type: list
links:
  - title: "Smoking behind supermarket with you"
    url: "https://smoking-behind-the-supermarket-with-you.online/"
    description: "Sasaki-san, why are you so dense, eh?"
  - title: "Adopting protagonist changed the genre"
    url: "https://comix.to/title/3ezr0-adopting-the-protagonist-changed-the-genre"
    description: "Before otome game starts, villainess tries to save herself"
  - title: "[32/32] Noble lady reformation guide"
    url: https://asurascans.com/comics/noble-lady-reformation-guide-89829cb7/
    description: Teaching young lady some magic
  - title: "Not your monster-in-law"
    url: https://comix.to/title/w0wj9-not-your-monster-in-law
    description: "Reincarnator were sold into marriage as mother-and-low and then her husband died"
  - title: "re:Life"
    url: https://mangadex.org/title/6e3553b9-ddb5-4d37-b7a3-99998044774e/relife
    description: "Kaizaki Arata no hanashibanashi"
