page:
  title: Manga reading
  type: list
links:
  - title: "[28/28] Noble lady reformation guide"
    url: https://asurascans.com/comics/noble-lady-reformation-guide-89829cb7/
    description: Teaching young lady some magic
  - title: "re:Life"
    url: https://mangadex.org/title/6e3553b9-ddb5-4d37-b7a3-99998044774e/relife
    description: "Kaizaki Arata no hanashibanashi"
