page:
  title: Manga reading
  type: list
links:
  - title: "[28/28] Noble lady reformation guide"
    url: https://asurascans.com/comics/noble-lady-reformation-guide-89829cb7/
    description: Teaching young lady some magic
