page:
  type: list
  title: "РФ"
links:
  - url: "https://speshu.ai/"
    title: "SpeShu"
    description: "Единое окно в мир ИИ"
  - url: https://nanobananna.ru/
    title: "nano bananna"
    description: "Генератор изображений онлайн"
  - url: "https://most-ai.com/"
    title: "Most"
    description: "80+ нейросетей в одном сервисе"
  - url: "https://vlex-ai.io/"
    title: "Влекс АИ"
    description: "Агрегатор Нейросетей для генерации текста, изображений, видео и озвучки"
