page:
  type: list
  title: "РФ"
links:
  - url: "https://speshu.ai/"
    title: "SpeShu"
    description: "Единое окно в мир ИИ"
  - url: https://nanobananna.ru/
    title: "nano bananna"
    description: "Генератор изображений онлайн"
