page:
  title: Games
  type: list
links:
  - title: POE2 planner
    url: https://poeplanner.com/poe2
    description: "Passive tree editor and more"
  - title: Maxroll.gg
    url: https://maxroll.gg/poe2
    description: "Planner for POE2"
