page:
  type: "kanji"
  title: "Адрес"

kanji:
 - char: "住"
   readings: "す, じゅう"
   meaning: "Жить, обитать"
   examples:
     - kanji: "住まい"
       reading: "すまい"
       meaning: "Жильё"
     - kanji: "住所"
       reading: "じゅうしょ"
       meaning: "Адрес"
     - kanji: "住民"
       reading: "じゅうみん"
       meaning: "Житель"

 - char: "所"
   readings: "ところ, しょ, じょ"
   meaning: "Место"
   examples:
     - kanji: "所"
       reading: "ところ"
       meaning: "Место"
     - kanji: "台所"
       reading: "だいどころ"
       meaning: "Кухня"
     - kanji: "場所"
       reading: "ばしょ"
       meaning: "Место"
     - kanji: "近所"
       reading: "きんじょ"
       meaning: "Окрестности"

 - char: "京"
   readings: "きょう"
   meaning: "Столица"
   examples:
     - kanji: "東京"
       reading: "とうきょう"
       meaning: "Токио"
     - kanji: "京都"
       reading: "きょうと"
       meaning: "Киото"

 - char: "都"
   readings: "みやこ, と, つ"
   meaning: "Столица, метрополия"
   examples:
     - kanji: "都"
       reading: "みやこ"
       meaning: "Столица"
     - kanji: "東京都"
       reading: "とうきょうと"
       meaning: "Метрополия Токио"
     - kanji: "都合"
       reading: "つごう"
       meaning: "Обстоятельства"
     - kanji: "首都"
       reading: "しゅと"
       meaning: "Столица страны"

 - char: "府"
   readings: "ふ"
   meaning: "Префектура (Киото/Осака)"
   examples:
     - kanji: "京都府"
       reading: "きょうとふ"
       meaning: "Префектура Киото"

 - char: "県"
   readings: "あがた, けん"
   meaning: "Префектура"
   examples:
     - kanji: "県"
       reading: "あがた"
       meaning: "Префектура"
     - kanji: "山口県"
       reading: "やまぐちけん"
       meaning: "Префектура Ямагути"

 - char: "市"
   readings: "し, いち"
   meaning: "Город, рынок"
   examples:
     - kanji: "京都市"
       reading: "きょうとし"
       meaning: "Город Киото"
     - kanji: "市長"
       reading: "しちょう"
       meaning: "Мэр"
     - kanji: "市場"
       reading: "いちば"
       meaning: "Рынок"

 - char: "区"
   readings: "く"
   meaning: "Район (городской)"
   examples:
     - kanji: "地区"
       reading: "ちく"
       meaning: "Район, округ"

 - char: "町"
   readings: "ちょう, まち"
   meaning: "Город, посёлок"
   examples:
     - kanji: "町"
       reading: "まち"
       meaning: "Город/Посёлок"
     - kanji: "下町"
       reading: "したまち"
       meaning: "Нижний город"
     - kanji: "町長"
       reading: "ちょうちょう"
       meaning: "Мэр города"

 - char: "村"
   readings: "むら, そん"
   meaning: "Деревня"
   examples:
     - kanji: "村"
       reading: "むら"
       meaning: "Деревня"
     - kanji: "村長"
       reading: "そんちょう"
       meaning: "Староста"

