page:
  type: "list"
  title: "nhee"
links:
  - title: "Yume.ktalk"
    url: "https://yumecenter.ktalk.ru/jck4jp0hoh3l"
    description: "Занятия проходят теперь здесь"
  - title: "OTUS DevOps"
    url: "https://otus.ru/learning/173394/"
    description: "DevOps@OTUS"
  - title: "Monkey type"
    url: "https://monkeytype.com"
    description: "Trying to improve"
