page:
  type: "list"
  title: "kaineer at web"
links:
  - title: "twitter"
    url: "https://twitter.com/kaineer"
    description: "almost ancient, yet still sane"
  - title: "github"
    url: "https://github.com/kaineer"
    description: "Coding in everything. Mostly in JS, for now"
  - title: "telegram"
    url: "https://t.me/kaineer"
    description: "Come, talk to me"
  - title: "duolingo"
    url: "https://www.duolingo.com/profile/kaineer"
    description: "Green owl, creepy"
