page:
  type: "list"
  title: "nhee"
links:
  - title: "Yume.zoom"
    url: "https://us02web.zoom.us/j/85667645171?pwd=9V9lALZmoG0z0qIeQmK48XQRcl9hWe.1"
  - title: "OTUS DevOps"
    url: "https://otus.ru/learning/173394/"
  - title: "Monkey type"
    url: "https://monkeytype.com"
